language: node_js
node_js:
  - '13'
  - '12'
  - '11'
  - '10'
  - '8'
install: npm ci
script: npm run mocha
jobs:
  include:
    - stage: lint
      node_js: 13
      script: npm run lint
    - stage: test
notifications:
  email: false
before_install: |
  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
    # caching feature creates `~/npm` for us
    cd ~/npm && npm install npm
    cd -
  } || true
  # avoids bugs around https://github.com/travis-ci/travis-ci/issues/5092
  export PATH=~/npm/node_modules/.bin:$PATH
# this avoids compilation in most cases (where we don't need it)
cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm

