language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
dist: trusty
sudo: false
